language: python
python:
  - "2.7"

env:
  - VERSION="8.0" LINT_CHECK="1"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
  - VERSION="8.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - sudo pip install magento
  - sudo pip install beautifulsoup4
  - git clone https://github.com/OCA/connector ${HOME}/connector -b ${VERSION}
  - git clone https://github.com/OCA/connector-ecommerce ${HOME}/connector-ecommerce -b ${VERSION}
  - git clone https://github.com/OCA/sale-workflow ${HOME}/sale-workflow -b ${VERSION}
  - git clone https://github.com/OCA/e-commerce ${HOME}/e-commerce -b ${VERSION}
  - git clone https://github.com/OCA/product-attribute ${HOME}/product-attribute -b ${VERSION}
  - git clone https://github.com/OCA/server-tools ${HOME}/server-tools -b ${VERSION}
  - printf '[options]\n\nrunning_env = dev' > ${HOME}/.openerp_serverrc
  # DO NOT MERGE. Only used to get a correct build in the WIP branch
  - git config --global user.email "travis@example.com"
  - git config --global user.name "travis"
  - pushd ${HOME}/connector
  - git pull --no-edit origin pull/46/head
  - git pull --no-edit origin pull/47/head
  - popd
  - pushd ${HOME}/e-commerce
  - git pull --no-edit origin pull/35/head
  - git pull --no-edit origin pull/34/head
  - popd
  - pushd ${HOME}/connector-ecommerce
  - git pull --no-edit origin pull/18/head
  - popd

script:
  - travis_run_tests

after_success:
  coveralls
